"""
Mission Role — dynamic observation priorities from an external advisor.

Architecture:
    Persona Config (YAML)
        ↓
    MissionRoleProvider (interface)
        ├── LLMProvider (today)
        ├── RuleProvider (future)
        ├── CloudProvider (future)
        └── HumanProvider (future)
        ↓
    MissionRoleCache (TTL-gated, thread-safe)
        ↓
    RoleEngine.effective_weight() = IntrinsicRole + MissionRole
        ↓
    Curiosity (unchanged — just reads effective role_weight)

Key invariants:
1. LLM is Advisor, not Controller — outputs class weights, never actions
2. Mission is TTL-based — expires automatically, Runtime works without it
3. Provider is abstract — Runtime doesn't know or care about the source
"""

import time
import threading
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from runtime.role.persona import Persona

logger = logging.getLogger("Role.Mission")


# ── Observation Context ──

@dataclass
class ObservationContext:
    """Snapshot of current environment for the LLM advisor.

    Purposefully minimal — enough to make informed suggestions,
    NOT enough to control the Runtime.
    """

    runtime_state: str = "idle"             # IDLE/FOCUS/ALERT/SLEEP
    active_classes: List[str] = field(default_factory=list)    # class_names currently active
    active_summary: List[Dict] = field(default_factory=list)   # [{class, count, avg_interest}, ...]
    top_importance: List[Dict] = field(default_factory=list)   # [{class, interactions, sessions}, ...]
    total_entities: int = 0
    active_count: int = 0

    def summary_text(self) -> str:
        """One-line summary for LLM prompt context."""
        active_str = ", ".join(
            f"{a.get('class','?')}(×{a.get('count',1)})"
            for a in self.active_summary[:10]
        ) or "none"
        imp_str = ", ".join(
            f"{i.get('class','?')}({i.get('interactions',0)}ev)"
            for i in self.top_importance[:5]
        ) or "none"
        return (
            f"State={self.runtime_state}, Entities={self.total_entities} "
            f"({self.active_count} active), Active: {active_str}, "
            f"Top importance: {imp_str}"
        )

    def to_dict(self) -> Dict:
        return {
            "runtime_state": self.runtime_state,
            "active_classes": self.active_classes,
            "active_summary": self.active_summary,
            "top_importance": self.top_importance,
            "total_entities": self.total_entities,
            "active_count": self.active_count,
        }


# ── Mission Role ──

@dataclass
class MissionRole:
    """Weight map from class_name → mission priority (0.0–1.0).

    Generated by a MissionRoleProvider. Cached with TTL.
    """

    weights: Dict[str, float] = field(default_factory=dict)
    expires_at: float = 0.0       # absolute time (monotonic) after which this is invalid
    generated_at: float = 0.0     # timestamp when generated
    reason: str = ""              # provider's explanation (for logging)
    provider_name: str = ""        # which provider generated this

    @property
    def is_expired(self) -> bool:
        return time.time() > self.expires_at

    @property
    def ttl_remaining(self) -> float:
        return max(0.0, self.expires_at - time.time())

    def get(self, class_name: str) -> float:
        """Get mission weight for a class, 0.0 if not specified."""
        return self.weights.get(class_name, 0.0)

    @classmethod
    def empty(cls, reason: str = "") -> "MissionRole":
        """Return a neutral mission role (no boosts)."""
        return cls(
            weights={},
            expires_at=0.0,
            reason=reason,
            provider_name="none",
        )

    def to_dict(self) -> Dict:
        return {
            "weights": self.weights,
            "expires_at": self.expires_at,
            "generated_at": self.generated_at,
            "ttl_remaining": self.ttl_remaining,
            "reason": self.reason,
            "provider_name": self.provider_name,
        }


# ── Mission Role Cache ──

class MissionRoleCache:
    """Thread-safe TTL cache for the current mission role.

    Properties:
    - Returns empty dict when expired or unset (graceful degradation)
    - Update is atomic (lock-held swap)
    - Time-source is monotonic (time.time)
    """

    def __init__(self):
        self._current: Optional[MissionRole] = None
        self._lock = threading.Lock()
        self._update_count: int = 0
        self._last_update: float = 0.0

    def get(self) -> MissionRole:
        """Return current MissionRole, or empty if expired/never set.

        DOES NOT block on LLM — returns immediately.
        """
        with self._lock:
            if self._current is None:
                return MissionRole.empty("never set")
            if self._current.is_expired:
                return MissionRole.empty("expired")
            return self._current

    def update(self, mission: MissionRole):
        """Atomically swap in a new mission role."""
        with self._lock:
            mission.generated_at = time.time()
            self._current = mission
            self._update_count += 1
            self._last_update = time.time()
            logger.info(
                "MissionRole updated by %s: %d weights, TTL=%.0fs, reason=%s",
                mission.provider_name,
                len(mission.weights),
                mission.ttl_remaining,
                mission.reason,
            )

    def get_weight(self, class_name: str) -> float:
        """Convenience: get a single class weight (0.0 if not set)."""
        return self.get().get(class_name)

    @property
    def is_active(self) -> bool:
        """Is there a valid (non-expired) mission role?"""
        with self._lock:
            return self._current is not None and not self._current.is_expired

    @property
    def update_count(self) -> int:
        with self._lock:
            return self._update_count

    @property
    def summary(self) -> str:
        mission = self.get()
        if not mission.weights:
            return "MissionRole(empty)"
        top = sorted(mission.weights.items(), key=lambda x: x[1], reverse=True)[:5]
        return f"MissionRole({len(mission.weights)} weights, ttl={mission.ttl_remaining:.0f}s, top={top})"


# ── Mission Role Provider (Abstract) ──

class MissionRoleProvider(ABC):
    """Abstract source of mission role weights.

    Runtime only calls generate(). It doesn't know or care
    whether the provider is LLM, rules, cloud, or human.
    """

    @abstractmethod
    def generate(self, persona: Persona, context: ObservationContext) -> MissionRole:
        """Generate mission role weights.

        Args:
            persona: Current persona configuration
            context: Current environment snapshot

        Returns:
            MissionRole with weights and TTL. Must return MissionRole.empty()
            on any failure — never raise.
        """
        ...

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Human-readable provider name for logging."""
        ...


# ── Factory ──

def create_mission_provider(provider_type: str = "llm") -> MissionRoleProvider:
    """Create a MissionRoleProvider by type name.

    Args:
        provider_type: "llm" | "rule" | "none"

    Returns:
        MissionRoleProvider instance.
    """
    if provider_type == "llm":
        from runtime.role.mission_llm import LLMMissionProvider
        return LLMMissionProvider()
    elif provider_type == "rule":
        from runtime.role.mission_llm import RuleMissionProvider
        return RuleMissionProvider()
    elif provider_type == "none":
        return _NullProvider()
    else:
        logger.warning("Unknown provider type '%s' — using null provider", provider_type)
        return _NullProvider()


class _NullProvider(MissionRoleProvider):
    """Provider that always returns empty — used when LLM is disabled."""

    def generate(self, persona: Persona, context: ObservationContext) -> MissionRole:
        return MissionRole.empty("null provider")

    @property
    def provider_name(self) -> str:
        return "null"
